export const ATTACK_MONSTER_CLICK = "ATTACK_MONSTER_CLICK";
export const BUY_HERO_DPS = "BUY_HERO_DPS";
export const ADD_NEW_HERO = "ADD_NEW_HERO";
export const INCREASE_CLICK_DAMAGE = "INCREASE_CLICK_DAMAGE";
